"""empty message

Revision ID: 25670c665b2a
Revises: 42d14941d8d5
Create Date: 2023-05-15 16:13:55.183305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25670c665b2a'
down_revision = '42d14941d8d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
