"""empty message

Revision ID: 44184cd6ec92
Revises: 
Create Date: 2023-05-15 15:20:07.257710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44184cd6ec92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Id пользователя'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Псеводним'),
    sa.Column('password', sa.Text(), nullable=False, comment='Хэш пароля'),
    sa.Column('registred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время регистрации пользователя.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Флаг активен ли пользователь.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
