"""1

Revision ID: 8d84933a6ee2
Revises: b416dd515072
Create Date: 2023-05-31 13:16:50.068315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d84933a6ee2'
down_revision = 'b416dd515072'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False, comment='Id проекта'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Краткое описание проекта.'),
    sa.Column('description', sa.Text(), nullable=False, comment='Подробное описание проекта'),
    sa.Column('photo_uris', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Список ссылок на фотографии проекта'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
